# Generated by Django 4.0.3 on 2022-03-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0002_booking_station_razorpaypayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('IRCTC-USER', 'IRCTC-USER')], default='IRCTC-USER', max_length=255),
        ),
    ]
